function [ method ] = cor_method( )
% Copyright 2011, Kenny Erleben

create_mesh            = @cor_create_mesh;
create_state           = @cor_create_state;
implicit_step          = @cor_implicit_step;
compute_elastic_forces = @cor_compute_elastic_forces;
semi_implicit_step     = @cor_semi_implicit_step;
clear_forces           = @cor_clear_forces;
add_surface_traction   = @cor_add_surface_traction;
compute_kinetic_energy = @cor_compute_kinetic_energy;

method = struct(...
  'create_mesh', create_mesh,...
  'create_state', create_state,...
  'implicit_step', implicit_step,...
  'compute_elastic_forces', compute_elastic_forces,...
  'semi_implicit_step', semi_implicit_step,...
  'clear_forces', clear_forces,...
  'add_surface_traction', add_surface_traction,...
  'compute_kinetic_energy', compute_kinetic_energy...
  );

end