% Copyright 2011, Kenny Erleben
clear all;
close all;
clc;

addpath('../fem');
addpath('../cor');
addpath('../fvm');
addpath('../meshing');

addpath('./exp_pull_gravity');

method = fem_method();

stiffness = [0.0, 1e5, 1e7];

cable = [-65, 0.0, 0.0];
gran = 1;
for i = 2:130/gran+1
    cable = [cable; cable(end, :) + [gran, 0.0, 0.0]];
end

for s = 1:length(stiffness)
    k = stiffness(s);
    % Create the scene for the simulation
    scene  = pull_gravity_create_scene(1, '../', cable, 'model1.12.mat');
    % Create the parameters for 'ecoflex-00-50' silicone, and use an adaptive
    % step in the simulation
    params = create_params('ecoflex-00-50','adaptive', 1.0, 0.001, false, true, 4, 1e9, true); 
    params.k = k;
    outputFolder = strcat('exp_pull_gravity/output/exp_pull_gravity_k=', string(k), '/');
    if ~exist(outputFolder, 'dir')
       mkdir(outputFolder)
    end
    % Create profile info
    pinfo  = create_profile_info();
    pinfo.output_path = outputFolder;
    % Data generated by the simulation
    pdata = simulate( params, method, scene, pinfo); 
    save(strcat('exp_pull_gravity/results/exp_pull_gravity_k=', string(k), '_pdata.mat'), 'pdata');
    save(strcat('exp_pull_gravity/results/exp_pull_gravity_k=', string(k), '_pinfo.mat'), 'pinfo');
end
