% Copyright 2011, Kenny Erleben
clear all;
close all;
clc;

addpath('../fem');
addpath('../cor');
addpath('../fvm');
addpath('../meshing');

addpath('./exp_pull_1');

method = fem_method();

stiffness = [1e5, 5e5, 1e6, 2.5e6, 5e6, 1e7];
%stiffness = [2.5e6];

cable = [0.0, 0.0, 69.9];
gran = 1.0058;
for i = 2:ceil(140/gran)
    cable = [cable; cable(end, :) - [0.0, 0.0, gran]];
end

for s = 1:length(stiffness)
    k = stiffness(s);
    % Create the scene for the simulation
    scene  = pull_create_scene(1, '../', cable, 'model1.12_upside_down.mat');
    % Create the parameters for 'ecoflex-00-50' silicone, and use an adaptive
    % step in the simulation
    params = create_params('ecoflex-00-50','adaptive', 0.98, 0.001, false, true, 1.5, 1e9, false); 
    params.k = k;
    params.E = 50000;
    %params.rho = 1070 / (0.2642e9 / params.E);
    % Make directory if it doesn't exist
    outputFolder = strcat('exp_pull_1/output/exp_pull_1_k=', string(k), '/');
    if ~exist(outputFolder, 'dir')
       mkdir(outputFolder)
    end
    % Create profile info
    pinfo  = create_profile_info();
    pinfo.output_path = outputFolder;
    % Data generated by the simulation
    pdata = simulate( params, method, scene, pinfo); 
    save(strcat('exp_pull_1/results/exp_pull_1_k=', string(k), '_pdata.mat'), 'pdata');
    save(strcat('exp_pull_1/results/exp_pull_1_k=', string(k), '_pinfo.mat'), 'pinfo');
end
