function [ KE ] = fvm_compute_kinetic_energy( state )
% Copyright 2011, Kenny Erleben

KE = 0.5 * (...
    state.vx' * (state.vx .* state.M)...
  + state.vy' * (state.vy .* state.M)...
  + state.vz' * (state.vz .* state.M)...
  ) ;
end